FROM golang:1.25.4-alpine

WORKDIR /app

RUN mkdir -p /.cache && chmod 777 /.cache

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
